//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSAApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Values {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Values() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LSAApp.Values", typeof(Values).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkiyede yastık altında oldugu tahmin edilen altın miktarının 5 bin ton oldugunu, bunun 200 milyar dolara tekabul ettigini belirterek, söz konusu rakamın buyuk bölumunun ev almak ya da başka önemli ihtiyaçlar için kiralık kasa, ev ya da kuyumcularda uzun yıllar atıl kaldıgını söyledi.
        ///Devlet otoriteleri tarafından yastık altından altınların çıkarılması projesine saglanacak destek ve teşvikle kayıt dışı altın tasarruflarının önemli bir bölumunun kısa sure içerisinde finansal sisteme girecegini ifade eden H [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Finans {
            get {
                return ResourceManager.GetString("Finans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkiyede.
        /// </summary>
        internal static string FinansTest {
            get {
                return ResourceManager.GetString("FinansTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaziantep&apos;te makineleşme, moda ve hazır giyimin gelişmesi nedeniyle eskisi kadar ilgi görmeyen ipekli dokuma kutnu kumaşı, Kültür ve Turizm Bakanlığının da desteğiyle yaşatılmaya çalışılıyor.
        ///
        ///Her kumaşın, her desenin bir adı var. &quot;Sultan&quot;, &quot;kerasi&quot;, &quot;sarı tas&quot;, &quot;mor sümbül&quot;... Kendi arasında 60&apos;a yakın motifi bulunan, ipek ve pamuk karışımı naturel kumaş kutnu, &quot;kara tezgah&quot; ve el tezgahlarında, baba mesleğinin sürdürülmesi gayesiyle dokunuyor. 16&apos;ncı yüzyıldan itibaren Gaziantep&apos;te dokunan ve Osmanlı pa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kultur {
            get {
                return ResourceManager.GetString("Kultur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zirveden düşen Kartal Milan sendromu yaşıyor. Şampiyonluk yarışını kendi sahasında
        ///aldığı başarısız sonuçlarla kaybeden bir diğer takım ise Milan oldu. Son
        ///şampiyonluğunu 2003-04 sezonunda yaşayan Milan için San Siro bu yıl tam bir
        ///kâbus oldu. Çizme&apos;nin devi bu sezon kendi sahasında ilk galibiyetini almak için
        ///tam 9 hafta bekledi. Ligin 18. haftasında kendi sahasında Napoli&apos;yi 5-2 yenerek
        ///ilk galibiyetini alan Milan, San Siro&apos;da şu ana kadar oynadığı 16 karşılaşmanın
        ///sadece 5&apos;inde sahadan 3 puanla ayrıldı.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ozet1 {
            get {
                return ResourceManager.GetString("Ozet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spor Toto Süper Lig&apos;de konuk olduğu Kasımpaşa&apos;yı 2-1 yenerek çıkışını sürdüren Galatasaray&apos;da Portekizli futbolcu Armindo Bruma, sergilediği başarılı performansla göz dolduruyor.
        ///
        ///Galatasaray&apos;ın bu sezon gol yollarındaki en etkili isimlerinden biri olan ve Kasımpaşa maçında da takımına galibiyeti getiren golü kaydeden Portekizli futbolcu, beklentileri fazlasıyla karşılarken, yıldızını da parlatmaya devam ediyor.
        ///
        ///Portekiz&apos;in Sporting Lizbon ekibinden 2013-2014 sezonu öncesinde 10 milyon avro bonservis b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Spor {
            get {
                return ResourceManager.GetString("Spor", resourceCulture);
            }
        }
    }
}
